### ISSUE TITLE
New test config breaks when using data on Jade

### ISSUE THREAD

**Issue by DanMMX** [DaftMonk/generator-angular-fullstack#1178]
I usually have a `locales.json` file for all my templating, the set up was usually straight forward just as 

```javascript
          data: function() {
            var locales = require('./server/config/locales.json');
            return locales;
          }
```

On [this](https://bitbucket.org/DanMMX/seed-project) project, created from v3.0.0-rc3 on `canary` branch, I tried to use that approach, but with the latest updates (can't find exactly the difference) I'm getting this when running `grunt test`

```javascript

  1) "after all" hook

  8 passing (5s)
  1 failing

  1) User API: "after all" hook:
     Uncaught /Users/dan/Documents/projects/toyota/web/client/app/account/login/login.jade:5
    3|   .row
    4|     .col-sm-12
  > 5|       h1= titles.login
    6|       p= login.comment
    7| 
    8|     .col-sm-12

Cannot read property 'login' of undefined
  TypeError: client/app/account/login/login.jade:5
      3|   .row
      4|     .col-sm-12
    > 5|       h1= titles.login
      6|       p= login.comment
      7| 
      8|     .col-sm-12
  
  Cannot read property 'login' of undefined
    at eval (<anonymous>:26:61)
    at eval (<anonymous>:196:22)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
  



Warning: Task "mochaTest:integration" failed. Use --force to continue.

Aborted due to warnings.

```

If you see the [commits](https://bitbucket.org/DanMMX/seed-project/commits/branch/master), the one that adds jade templating with `locales.json` makes it break. After reverting that commit, `grunt test` works again.

On [this](https://bitbucket.org/DanMMX/casacuestacentro), other project, created with v2.0.13 in `canary` branch as well, I have the same approach of `data` on the jade but its `grunt test` task works as expected.

Any ideas?

PS. The one that breaks on test runs perfectly fine on `grunt serve`

**Comment by DanMMX** [comment]
Found the error

on `karma.conf` in the `ngJade2JsPreprocessor` you should add that same `data` as following:

```javascript

    ngJade2JsPreprocessor: {
     stripPrefix: 'client/',
     locals: require('./server/config/locales.json')
    },

```
