### ISSUE TITLE
[3.0.0-rc3] yo fails on build

### ISSUE THREAD

**Issue by macneib** [DaftMonk/generator-angular-fullstack#1180]
````
yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js
````
````
1.4.7
/home/macneib/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
linux { http_parser: '1.0',
  node: '0.10.37',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1l' }
cat: Gruntfile.js: No such file or directory
````

````
# Client

? What would you like to write scripts with? JavaScript + Babel
? What would you like to write markup with? Jade
? What would you like to write stylesheets with? Less
? What Angular router would you like to use? ngRoute
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? What would you like to use for data modeling? Mongoose (MongoDB)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? 
? Would you like to use socket.io? Yes

# Project

? What would you like to write tests with? Mocha + Chai + Sinon
? What would you like to write Chai assertions with? Expect
````
````
Initializing yo-rc.json configuration.


events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at destinationPath (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:80:13)
    at Object.relativeRequire (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:88:8)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/script-base.js:40:25)
    at eval (eval at template (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:8:11)
    at underscore (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at Generator.actions.engine (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:216:32)
    at Generator.template (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:191:19)
    at /usr/local/lib/node_modules/generator-angular-fullstack/util.js:158:14
    at Array.forEach (native)
    at Object.processDirectory (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:128:9)
````

**Comment by kingcody** [comment]
This is a node version issue. `path.isAbsolute` was not introduced until `v0.12.x`. We're tentatively requiring node `v0.12.x` for the `3.0.0` release. Do you have any issues with using a `v0.12.x` release of node?

**Comment by kingcody** [comment]
Btw, thanks for the detailed report; it really helps.

**Comment by macneib** [comment]
Works for me!  Thanks for the help!

**Comment by kingcody** [comment]
@macneib I just want to get some additional feedback. We felt that the v0.12 branch had been public for long enough to consider it a requirement, also we really want to start using the new features that it has to offer. With your experience, do you foresee any issues with users being required to use node >= v0.12?

**Comment by macneib** [comment]
On my main app I'm still running v0.10.37, which I'm upgrading as I type this.
That being said, any new project should be at least v0.12.2.
My reasoning is that because this is such a massive update to this generator it would be the best time to enforce a version bump.

**Comment by kingcody** [comment]
You're correct. Was committing the changes while I read your response (:
