### ISSUE TITLE
npm 2.0.0 installing Release Candidate

### ISSUE THREAD

**Issue by smirciat** [DaftMonk/generator-angular-fullstack#1184]
Cloud 9 is using npm 2.0.0 by default, and running "npm install generator-angular-fullstack" is grabbing version 3.0.0rc3 by default.  Is this the expected behavior?  Either way, I get a build error on generation, easily fixed by commenting out the if condition on line 80:
```
? What would you like to write tests with? Jasmine
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.


events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at destinationPath (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:80:13)
    at Object.relativeRequire (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:88:8)
    at Generator.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/script-base.js:40:25)
    at eval (eval at template (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:8:11)
    at underscore (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at Generator.actions.engine (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:216:32)
    at Generator.template (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:191:19)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:158:14
    at Array.forEach (native)
    at Object.processDirectory (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:128:9)
```

**Comment by DanMMX** [comment]
Give a look at #1180

**Comment by smirciat** [comment]
Thanks
