### ISSUE TITLE
TypeError: Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by sangd** [DaftMonk/generator-angular-fullstack#1197]
I'm getting the following error while trying the 3.0.0-rc4. Any idea how to fix this? Thanks.

#### Client
? What would you like to write scripts with? JavaScript
? What would you like to write markup with? Jade
? What would you like to write stylesheets with? Sass
? What Angular router would you like to use? ngRoute
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes
#### Server
? What would you like to use for data modeling? Mongoose (MongoDB)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? Google
? Would you like to use socket.io? Yes
#### Project
? What would you like to write tests with? Jasmine
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at destinationPath (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:80:13)
    at Object.relativeRequire (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:88:8)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/script-base.js:40:25)
    at eval (eval at template (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6306:22), <anonymous>:8:11)
    at underscore (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/util/engines.js:23:45)
    at Generator.actions.engine (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:216:32)
    at Generator.template (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/actions/actions.js:191:19)
    at /usr/local/lib/node_modules/generator-angula

**Comment by kingcody** [comment]
`path.isAbsolute` was not added until node `>=0.12.0`. The `3.0.0` release of `generator-angular-fullstack` is currently requiring a [node `>=0.12.0`](https://github.com/DaftMonk/generator-angular-fullstack/blob/canary/package.json#L53).

**Comment by sangd** [comment]
@kingcody that's the issue. Thanks.
