### ISSUE TITLE
Generators throw exception in 3.0.0rc6

### ISSUE THREAD

**Issue by leonfeng** [DaftMonk/generator-angular-fullstack#1263]
After updating to 3.0.0rc6, `yo angular-fullstack` and `yo angular-fullstack:endpoint stuff` fail to run on my system. Here's the error message for `yo angular-fullstack`:
```
/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:7:28)
    at Module._compile (module.js:460:26)
```
And here's the error message for `yo angular-fullstack:endpoint stuff`:
```
/usr/local/lib/node_modules/generator-angular-fullstack/endpoint/generator.js:3
import path from 'path';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/endpoint/index.js:7:28)
    at Module._compile (module.js:460:26)
```
Everything else works fine though. Haven't tried deploying yet. Reinstalled `generator-angular-fullstack` multiple times with both node and iojs. Same results.

My setup:
* OS X 10.10.5
* zsh 5.0.8
* n 2.0.2
  * node 0.12.7
  * iojs 3.2.0

**Comment by leonfeng** [comment]
Downgraded to 3.0.0rc5 and both fullstack and endpoint generation work again.

**Comment by Awk34** [comment]
Yes, this will be fixed in the next RC.
