### ISSUE TITLE
Stopping Express server

### ISSUE THREAD

**Issue by shahar84** [DaftMonk/generator-angular-fullstack#1267]
Hi there,

I heard great things about this generator - and I would love to give it a go!
The yeoman installation go smoothly but when I try to run it via the **grunt serve** command im getting the following error:
```
Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
/Applications/MAMP/htdocs/nadlan/server/app.js:7
import express from 'express';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/nadlan/server/index.js:12:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Stopping Express server
```

I have spent couple of hours trying to make it work but no success:( 
I would really appreciate it if someone could give me a hand here - and thanks in advance!!

**Comment by kingcody** [comment]
@shahar84 this bug was recently fixed in `canary`. We'll release the fix soon; but in the mean time you can simply do this:
**server/index.js**
```diff
// Set default node environment to development
var env = process.env.NODE_ENV = process.env.NODE_ENV || 'development';

-if (env === 'production' || env === 'test') {
+if (env === 'development' || env === 'test') {
  // Register the Babel require hook
  require('babel-core/register');
}
```

**Comment by Awk34** [comment]
In the mean time, you can install a previous version of the generator

**Comment by kingcody** [comment]
The OP has already generated a project. The previous version contained the bug that wouldn't allow the generator to be compiled at runtime if it was installed as a `node_module`.

**Comment by Awk34** [comment]
True, since that one line is the only thing breaking things..

**Comment by shahar84** [comment]
@kingcody that worked like a charm! 
I appreciate all of your help - now that the server is up and running I can give it a go:) 

Thanks everyone!

**Comment by Gregory-Han** [comment]
Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
D:\N_Biz\Dev\bz\server\app.js:7
import express from 'express';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\N_Biz\Dev\bz\server\index.js:12:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Stopping Express server
