### ISSUE TITLE
test with 3.0.0.-rc8

### ISSUE THREAD

**Issue by jjgonver** [DaftMonk/generator-angular-fullstack#1317]
I start to test version 3.0.0-rc8 and after execute grunt serve:

```
Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (18 files)

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (6 files)

Running "wiredep:client" (wiredep) task

Running "postcss:dist" (postcss) task

Running "express:dev" (express) task
Starting background Express server
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Agent.Server.listen (net.js:1267:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
```

Before I check all the Prerequisites:

```
- [Git](https://git-scm.com/)
- [Node.js and NPM](nodejs.org) >= v0.12.0
- [Bower](bower.io) (`npm install --global bower`)
- [Grunt](http://gruntjs.com/) (`npm install --global grunt-cli`)
- [SQLite](https://www.sqlite.org/quickstart.html)
````

**Comment by Awk34** [comment]
You probably have another process open listening on a port that your angular-fullstack app wants to listen on. If you can't find & close it, try restarting your computer and trying again.

**Comment by kingcody** [comment]
Exactly. Most likely another angular-fullstack app.

**Comment by jjgonver** [comment]
Ok. That was the problem. I restart the computer and It was resolved.
Thank you.
