### ISSUE TITLE
grunt serve:dist on the latest version

### ISSUE THREAD

**Issue by pihomeserver** [DaftMonk/generator-angular-fullstack#1326]
Hello,

I installed the latest version of the generator (with Sequelize but not MongoDB). Once installed, as soon as i run the command
```
grunt serve:dist
```
I got the following error message :
```
Running "express:prod" (express) task
Starting background Express server
/Users/xxx/Development/yyy/dist/server/sqldb/index.js:23
 new _sequelize2['default'](_configEnvironment2['default'].sequelize.uri, _con
                                                                    ^
TypeError: Cannot read property 'uri' of undefined
    at Object.<anonymous> (/Users/xxx/Development/yyy/dist/server/sqldb/index.js:23:81)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxx/Development/yyy/dist/server/app.js:13:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxx/Development/yyy/dist/server/index.js:12:28)
    at Module._compile (module.js:460:26)
Stopping Express server

Running "wait" task
>> Waiting for server reload...
Done waiting!

Running "open:server" (open) task

Running "express-keepalive" task
```
If you need any other information, feel free to ask

**Comment by kingcody** [comment]
In `server/config/environment/production.js` you need to add your production database settings for sequelize. You can look at `server/config/environment/development.js` for an example.

**Comment by pihomeserver** [comment]
Thanks.
