### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by salismt** [DaftMonk/generator-angular-fullstack#1328]
I cannot generate an app when run $ yo angular-fullstack <app-name>

    Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/salismt/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/env/index.js:6:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by kingcody** [comment]
It looks like the lodash dependency of `yeoman-generator` (which is a dep of `generator-angular-fullstack`) failed to install. Could you try removing and reinstalling

**Comment by Awk34** [comment]
Closing due to inactivity.
