### ISSUE TITLE
yo angular-fullstack:app not working in Node 4.1

### ISSUE THREAD

**Issue by clairtonluz** [DaftMonk/generator-angular-fullstack#1332]
```js
➜  project  yo angular-fullstack:app blog 
? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write scripts with? JavaScript
? Would you like to use Javascript ES6 in your client by preprocessing it with Babel? Yes
? What would you like to write markup with? HTML
? What would you like to write stylesheets with? CSS
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? Would you like to use mongoDB with Mongoose for data modeling? No
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.

   create .gitignore
   create bower.json
   create package.json
   create .bowerrc
   create .buildignore
   create .editorconfig
   create .gitattributes
   create .travis.yml
   create client/.htaccess
   create client/.jshintrc
   create client/app/app.css
   create client/app/app.js
   create client/app/main/main.controller.spec.js
   create client/app/main/main.controller.js
   create client/app/main/main.css
   create client/app/main/main.html
   create client/app/main/main.js
   create client/assets/images/yeoman.png
   create client/components/modal/modal.service.js
   create client/components/modal/modal.css
   create client/components/modal/modal.html
   create client/components/navbar/navbar.controller.js
   create client/components/navbar/navbar.html
   create client/favicon.ico
   create client/index.html
   create client/robots.txt
   create e2e/main/main.po.js
   create e2e/main/main.spec.js
   create Gruntfile.js
   create karma.conf.js
   create protractor.conf.js
   create server/.jshintrc
   create server/.jshintrc-spec
   create server/api/thing/index.js
   create server/api/thing/thing.controller.js
   create server/api/thing/thing.spec.js
   create server/app.js
   create server/components/errors/index.js
   create server/config/local.env.js
   create server/config/local.env.sample.js
   create server/config/environment/development.js
   create server/config/environment/index.js
   create server/config/environment/production.js
   create server/config/environment/test.js
   create server/config/express.js
   create server/routes.js
   create server/views/404.html


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


bower angular#>=1.2.*           cached git://github.com/angular/bower-angular.git#1.4.6
bower angular#>=1.2.*         validate 1.4.6 against git://github.com/angular/bower-angular.git#>=1.2.*
bower json3#~3.3.1              cached git://github.com/bestiejs/json3.git#3.3.2
bower json3#~3.3.1            validate 3.3.2 against git://github.com/bestiejs/json3.git#~3.3.1
bower es5-shim#~3.0.1           cached git://github.com/es-shims/es5-shim.git#3.0.2
bower es5-shim#~3.0.1         validate 3.0.2 against git://github.com/es-shims/es5-shim.git#~3.0.1
bower bootstrap#~3.1.1          cached git://github.com/twbs/bootstrap.git#3.1.1
bower bootstrap#~3.1.1        validate 3.1.1 against git://github.com/twbs/bootstrap.git#~3.1.1
bower angular-resource#>=1.2.*  cached git://github.com/angular/bower-angular-resource.git#1.4.6
bower angular-resource#>=1.2.*         validate 1.4.6 against git://github.com/angular/bower-angular-resource.git#>=1.2.*
bower angular-cookies#>=1.2.*            cached git://github.com/angular/bower-angular-cookies.git#1.4.6
bower angular-cookies#>=1.2.*          validate 1.4.6 against git://github.com/angular/bower-angular-cookies.git#>=1.2.*
bower angular-sanitize#>=1.2.*           cached git://github.com/angular/bower-angular-sanitize.git#1.4.6
bower angular-sanitize#>=1.2.*         validate 1.4.6 against git://github.com/angular/bower-angular-sanitize.git#>=1.2.*
bower font-awesome#>=4.1.0               cached git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower font-awesome#>=4.1.0             validate 4.4.0 against git://github.com/FortAwesome/Font-Awesome.git#>=4.1.0
bower lodash#~2.4.1                      cached git://github.com/lodash/lodash.git#2.4.2
bower lodash#~2.4.1                    validate 2.4.2 against git://github.com/lodash/lodash.git#~2.4.1
bower angular-ui-router#~0.2.15          cached git://github.com/angular-ui/ui-router.git#0.2.15
bower angular-ui-router#~0.2.15        validate 0.2.15 against git://github.com/angular-ui/ui-router.git#~0.2.15
bower angular-mocks#>=1.2.*              cached git://github.com/angular/bower-angular-mocks.git#1.4.6
bower angular-mocks#>=1.2.*            validate 1.4.6 against git://github.com/angular/bower-angular-mocks.git#>=1.2.*
bower angular-scenario#>=1.2.*           cached git://github.com/angular/bower-angular-scenario.git#1.4.6
bower angular-scenario#>=1.2.*         validate 1.4.6 against git://github.com/angular/bower-angular-scenario.git#>=1.2.*
bower angular-bootstrap#~0.11.0      not-cached git://github.com/angular-ui/bootstrap-bower.git#~0.11.0
bower angular-bootstrap#~0.11.0         resolve git://github.com/angular-ui/bootstrap-bower.git#~0.11.0
bower angular-bootstrap#~0.11.0        download https://github.com/angular-ui/bootstrap-bower/archive/0.11.2.tar.gz
bower jquery#>= 1.9.0                    cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#>= 1.9.0                  validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower angular-bootstrap#~0.11.0         extract archive.tar.gz
bower angular-bootstrap#~0.11.0    invalid-meta angular-bootstrap is missing "ignore" entry in bower.json
bower angular-bootstrap#~0.11.0        resolved git://github.com/angular-ui/bootstrap-bower.git#0.11.2
bower json3#~3.3.1                      install json3#3.3.2
bower es5-shim#~3.0.1                   install es5-shim#3.0.2
bower angular#>=1.2.*                   install angular#1.4.6
bower font-awesome#>=4.1.0              install font-awesome#4.4.0
bower angular-resource#>=1.2.*          install angular-resource#1.4.6
bower angular-ui-router#~0.2.15         install angular-ui-router#0.2.15
bower lodash#~2.4.1                     install lodash#2.4.2
bower bootstrap#~3.1.1                  install bootstrap#3.1.1
bower angular-cookies#>=1.2.*           install angular-cookies#1.4.6
bower angular-sanitize#>=1.2.*          install angular-sanitize#1.4.6
bower jquery#>= 1.9.0                   install jquery#2.1.4
bower angular-scenario#>=1.2.*          install angular-scenario#1.4.6
bower angular-mocks#>=1.2.*             install angular-mocks#1.4.6
bower angular-bootstrap#~0.11.0         install angular-bootstrap#0.11.2

json3#3.3.2 client/bower_components/json3

es5-shim#3.0.2 client/bower_components/es5-shim

angular#1.4.6 client/bower_components/angular

font-awesome#4.4.0 client/bower_components/font-awesome

angular-resource#1.4.6 client/bower_components/angular-resource
└── angular#1.4.6

angular-ui-router#0.2.15 client/bower_components/angular-ui-router
└── angular#1.4.6

lodash#2.4.2 client/bower_components/lodash

bootstrap#3.1.1 client/bower_components/bootstrap
└── jquery#2.1.4

angular-cookies#1.4.6 client/bower_components/angular-cookies
└── angular#1.4.6

angular-sanitize#1.4.6 client/bower_components/angular-sanitize
└── angular#1.4.6

jquery#2.1.4 client/bower_components/jquery

angular-scenario#1.4.6 client/bower_components/angular-scenario
└── angular#1.4.6

angular-mocks#1.4.6 client/bower_components/angular-mocks
└── angular#1.4.6

angular-bootstrap#0.11.2 client/bower_components/angular-bootstrap
└── angular#1.4.6
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.1.0","npm":"2.14.3"})
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN optional dep failed, continuing fsevents@0.3.8
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
 
> phantomjs@1.9.18 install /home/clairton/project/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...
/ [======================================--] 94% 0.0s\
Received 12854K total.
Extracting tar contents (via spawned process)
Removing /home/clairton/project/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1442920175276/phantomjs-1.9.8-linux-x86_64 -> /home/clairton/project/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/clairton/project/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
 
> kerberos@0.0.14 install /home/clairton/project/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/clairton/project/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: g++: Command not found
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 127
make: Leaving directory `/home/clairton/project/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/home/clairton/app/node/bin/node" "/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/clairton/project/node_modules/connect-mongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
 
> pngquant-bin@0.3.5 postinstall /home/clairton/project/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node index.js

✔ pre-build test passed successfully!
 
> jpegtran-bin@0.2.8 postinstall /home/clairton/project/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node index.js

✔ pre-build test passed successfully!

> gifsicle@0.1.7 postinstall /home/clairton/project/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node index.js

✔ pre-build test passed successfully!
 
> optipng-bin@0.3.11 postinstall /home/clairton/project/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node index.js

✔ pre-build test passed successfully!
 
> ws@0.4.32 install /home/clairton/project/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/clairton/project/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/clairton/project/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
 
> v8-debug@0.4.6 preinstall /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
>  

 
> v8-profiler@5.2.12 preinstall /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> ws@0.4.32 install /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/build'
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.0","npm":"2.14.3"})
 
> v8-profiler@5.2.12 install /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build'
  CXX(target) Release/obj.target/profiler/src/profiler.o
make: g++: Command not found
make: *** [Release/obj.target/profiler/src/profiler.o] Error 127
make: Leaving directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/home/clairton/app/node/bin/node" "/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64"
gyp ERR! cwd /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/clairton/app/node/bin/node /home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64/profiler.node --module_name=profiler --module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-28-generic
node-pre-gyp ERR! command "/home/clairton/app/node/bin/node" "/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/home/clairton/app/node/bin/node /home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64/profiler.node --module_name=profiler --module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.12/node-v46-linux-x64' (1)

> v8-debug@0.4.6 install /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
make: g++: Command not found
make: *** [Release/obj.target/debug/src/debug.o] Error 127
make: Leaving directory `/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-28-generic
gyp ERR! command "/home/clairton/app/node/bin/node" "/home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64"
gyp ERR! cwd /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/clairton/app/node/bin/node /home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64/debug.node --module_name=debug --module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.19.0-28-generic
node-pre-gyp ERR! command "/home/clairton/app/node/bin/node" "/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/home/clairton/app/node/bin/node /home/clairton/app/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64/debug.node --module_name=debug --module_path=/home/clairton/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64' (1)
npm ERR! Linux 3.19.0-28-generic
npm ERR! argv "/home/clairton/app/node/bin/node" "/home/clairton/app/node/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! v8-profiler@5.2.12 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.2.12 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/clairton/project/npm-debug.log
```

**Comment by Awk34** [comment]
One thing that tips me off this this line: `make: g++: Command not found`. Make sure you have g++ installed.

**Comment by Awk34** [comment]
You can also try just removing the `grunt-node-inspector` for now. It's not always necessary.

**Comment by occult** [comment]
@Awk34 I had a similar problem and removing grunt-node-inspector fixed it. Am I missing out on anything?

**Comment by Awk34** [comment]
You'll only ever use that module if you're running `grunt serve:debug`

**Comment by Awk34** [comment]
Closing in favor of #1329
