### ISSUE TITLE
$ grunt Loading "Gruntfile.js" tasks...ERROR >> Error: Cannot find module 'jit-grunt'

### ISSUE THREAD

**Issue by Artofacks1** [DaftMonk/generator-angular-fullstack#856]
Hello, I am geting this error and was wondering why its missing when i .... grunt

**Comment by kingcody** [comment]
Does `npm install --save-dev jit-grunt` resolve the issue?

**Comment by Artofacks1** [comment]
I'm actually getting this issue on grunt serve now. 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/robert/daftmonk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/robert/daftmonk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/robert/daftmonk/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
Done waiting!

**Comment by kingcody** [comment]
Is your mongodb running locally?

**Comment by Artofacks1** [comment]
Well, I am not sure. But I am only ... sudo npm install and I am getting this error

**Comment by dezechristophe** [comment]
how did you solve that please ?

**Comment by jamiecalder** [comment]
I was having this same issue, a fellow developer had pushed all of his node modules onto the repo and messed mine up. Tried to run npm install and was getting errors. In the end, I had to delete all of the contents of the node_modules folder and then do an npm install, to fix it.
