### ISSUE TITLE
grunt serve:debug wont stop at the first line

### ISSUE THREAD

**Issue by ndjordjevic** [DaftMonk/generator-angular-fullstack#865]
I got a fresh app generated and after running a grunt serve:debug everything looks fine but the Node Inspector wont stop execution at the first line. I'm using node v0.12. Not sure if this causes an issue. Anyone facing the same?

Thanks.

**Comment by anoopknayak** [comment]
I think I'm also facing a similar one When i run 
`grunt serve:debug`

I get this as the output
```
Running "serve:debug" (serve) task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "env:all" (env) task

Running "injector:less" (injector) task
Missing option `template`, using `dest` as template instead
Injecting less files (4 files)
>> Nothing changed

Running "concurrent:server" (concurrent) task

    Running "less:server" (less) task
    File .tmp/app/app.css created: 0 B → 151.41 kB

    Done, without errors.


    Execution Time (2015-03-09 05:07:58 UTC)
    loading tasks  194ms  ▇▇▇▇▇▇▇▇▇ 19%
    less:server    828ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 81%
    Total 1s

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (14 files)
>> Nothing changed

Running "injector:less" (injector) task
Missing option `template`, using `dest` as template instead
Injecting less files (4 files)
>> Nothing changed

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
>> Nothing changed

Running "wiredep:target" (wiredep) task

Running "autoprefixer:dist" (autoprefixer) task
File .tmp/app/app.css created.

Running "concurrent:debug" (concurrent) task
Running "node-inspector:custom" (node-inspector) task
Running "nodemon:debug" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug-brk server/app.js`
Debugger listening on port 5858
Node Inspector v0.9.1
Visit http://localhost:8080/debug?port=5858 to start debugging.
TypeError: undefined is not a function
    at DebugServer.debugAction (/Users/DevUser/Documents/develop/Apps/node_modules/grunt-node-inspector/node_modules/node-inspector/lib/debug-server.js:17:7)
    at next_layer (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/route.js:107:5)
    at /Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:195:24
    at Function.proto.process_params (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:189:19)
    at Layer.favicon [as handle] (/Users/DevUser/Documents/develop/Apps/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/serve-favicon/index.js:63:7)
    at trim_prefix (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:226:17)
    at /Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:198:9
    at Function.proto.process_params (/Users/DevUser/Documents/develop/Apps/node_modules/express/lib/router/index.js:251:12)
```

And node inspector doesn't work on that port...
