### ISSUE TITLE
Trouble deploying to Heroku

### ISSUE THREAD

**Issue by michaelcheng429** [DaftMonk/generator-angular-fullstack#869]
I'm probably missing something very simple, but I'm getting an "Internal Server Error" when I try to open the Heroku URL after doing grunt buildcontrol:heroku and following the instructions about adding MongoHQ and Facebook, Google, and Twitter. I've simply done the minimum to push to Heroku, haven't added anything, yet.

Here are the errors from "heroku logs." I'm guessing I just need to change something concerning the MongoDB configuration. Help would be appreciated. Thanks!

    Error: host must be specified [undefined]
    at new exports.ConnectionPool (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:15:11)
    at MongoStore._get_collection (/app/node_modules/connect-mongo/lib/connect-mongo.js:177:14)
    at MongoStore.get (/app/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
    at Server.connect (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:337:25)
    at Db.open (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:281:23)
    at /app/node_modules/express/lib/router/index.js:198:9
    at MongoStore._open_database (/app/node_modules/connect-mongo/lib/connect-mongo.js:182:15)
    at Layer.session [as handle] (/app/node_modules/express-session/index.js:204:11)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:226:17)
    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:251:12)
    at=info method=GET path="/favicon.ico" host=mevstoday.herokuapp.com request_id=43cf88a5-4971-447c-9962-483c92010a7b fwd="98.212.148.234" dyno=web.1 connect=1ms service=17ms status=500 bytes=206
    at /app/node_modules/connect-mongo/lib/connect-mongo.js:160:19
    at Layer.session [as handle] (/app/node_modules/express-session/index.js:204:11)

And:

```Error: Error getting collection: sessions
    at MongoStore.get (/app/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
    at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:251:12)
    at next (/app/node_modules/express/lib/router/index.js:189:19)
    at Db.collection (/app/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:524:27)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:226:17)
    at MongoStore._get_collection (/app/node_modules/connect-mongo/lib/connect-mongo.js:158:17)
    at /app/node_modules/express/lib/router/index.js:198:9
    at Layer.initialize [as handle] (/app/node_modules/passport/lib/middleware/initialize.js:62:5)```

**Comment by michaelcheng429** [comment]
Now I'm getting an error that says:

     Error: cannot determine state of server

**Comment by michaelcheng429** [comment]
I figured out the problem! Closing this issue.

**Comment by honkskillet** [comment]
What was the issue?

**Comment by michaelcheng429** [comment]
The Heroku URL gave me an "Internal Server Error" at first after doing `grunt buildcontrol:heroku`, but then I realized I needed to set the URL for my online MongoDB database.

**Comment by DrakeLeung** [comment]
@michaelcheng429  How to set the URL manually? I modified the `config/enviroment/production.js`, but doesn't work.

**Comment by gabrielsr** [comment]
@michaelcheng429 I would apreciate to know it, too.

**Comment by mariostesla** [comment]
in config/enviroment/production.js  , you have 
    
    mongo: {
        uri:    process.env.MONGOLAB_URI || ....
    }

open heroku dashboard ,then settings, then Config Variables and add a variable named "MONGOLAB_URI" with value the url of your database which would look something like this mongodb://username:password@***.mongolab.com:port/database

**Comment by michaelcheng429** [comment]
Heroku actually recommends using

    heroku config:add MONGOLAB_URI=databaseurl

It's either add or set. If you do this, you won't need to modify any of your files. But, for Heroku, I believe you may need to verify your credit card first. Make sure you don't add MongoHQ, or else you will start getting charged. Learned that the hard way =P.

**Comment by lifwanian** [comment]
Was having the same issue with having the correct URI. Fixed mine with updating `connect-mongo` to latest
