### ISSUE TITLE
Can't grunt serve, errors on wait task

### ISSUE THREAD

**Issue by danpaulsmith** [DaftMonk/generator-angular-fullstack#915]
Clean yo angular-fullstack install. Then trying to run grunt serve.

Have npm installed.

<pre><code>
Running "wait" task
>> Waiting for server reload...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/dansmith/Sites/heroku/test-board/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/dansmith/Sites/heroku/test-board/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/dansmith/Sites/heroku/test-board/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
</code></pre>

**Comment by danpaulsmith** [comment]
Ah my bad, 27017 is mongod
