### ISSUE TITLE
grunt serve:dist produces non-functional build

### ISSUE THREAD

**Issue by austinkettner** [DaftMonk/generator-angular-fullstack#982]
After countless hours of searching, testing and updating/reverting/etc I have been unable to get a functional distribution build of my angular application.

The core problem seems to be in how Angular is being processed during the 'uglify' stage. The resulting build deploys but via Chrome Inspector it has the following error...

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module inkhornWebsiteApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngAnimate due to:
Error: [$injector:nomod] Module 'ngAnimate' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.0/$injector/nomod?p0=ngAnimate
    at http://localhost:9000/app/fc6352c5.vendor.js:4:982
    at http://localhost:9000/app/fc6352c5.vendor.js:4:10271
    at b (http://localhost:9000/app/fc6352c5.vendor.js:4:9843)
    at http://localhost:9000/app/fc6352c5.vendor.js:4:10155
    at http://localhost:9000/app/fc6352c5.vendor.js:4:18826
    at f (http://localhost:9000/app/fc6352c5.vendor.js:4:1389)
    at n (http://localhost:9000/app/fc6352c5.vendor.js:4:18604)
    at http://localhost:9000/app/fc6352c5.vendor.js:4:18773
    at f (http://localhost:9000/app/fc6352c5.vendor.js:4:1389)
    at n (http://localhost:9000/app/fc6352c5.vendor.js:4:18604)
http://errors.angularjs.org/1.4.0/$injector/modulerr?p0=ngAnimate&p1=Error%…0n%20(http%3A%2F%2Flocalhost%3A9000%2Fapp%2Ffc6352c5.vendor.js%3A4%3A18604)
    at http://localhost:9000/app/fc6352c5.vendor.js:4:982
    at http://localhost:9000/app/fc6352c5.vendor.js:4:19032
    at f (http://localhost:9000/app/fc6352c5.vendor.js:4:1389)
    at n (http://localhost:9000/app/fc6352c5.vendor.js:4:18604)
    at http://localhost:9000/app/fc6352c5.vendor.js:4:18773
    at f (http://localhost:9000/app/fc6352c5.vendor.js:4:1389)
    at n (http://localhost:9000/app/fc6352c5.vendor.js:4:18604)
    at Ya (http://localhost:9000/app/fc6352c5.vendor.js:4:20294)
    at h (http://localhost:9000/app/fc6352c5.vendor.js:4:7915)
    at fa (http://localhost:9000/app/fc6352c5.vendor.js:4:8225)
http://errors.angularjs.org/1.4.0/$injector/modulerr?p0=inkhornWebsiteApp&p…0fa%20(http%3A%2F%2Flocalhost%3A9000%2Fapp%2Ffc6352c5.vendor.js%3A4%3A8225)
```

I have open sourced the repository so other can take a look, try to run a dist build and provide some feedback, any help would be appreciated though! The project resides in the 'redesign' branch of the repository, https://github.com/InkhornGames/InkhornWebsite/tree/redesign

**Comment by Awk34** [comment]
You need to import ngAnimate into your app, like so:

```js
angular.module('myApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ui.router',
    'ui.bootstrap',
    'ngMessages',
]).config(function() {});
```

**Comment by austinkettner** [comment]
@Awk34 I had ngAnimate in there but in a different spot, it was..

```angular.module 'inkhornWebsiteApp', [
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'ngAnimate',
  'btford.socket-io',
  'ui.router',
  'ui.tinymce'
]```

but I changed it to...
```
angular.module 'inkhornWebsiteApp', [
  'ngAnimate',
  'ngCookies',
  'ngResource',
  'ngSanitize',
  'btford.socket-io',
  'ui.router',
  'ui.tinymce'
]```

However, now I get the following error, even after playing with script loading order a ton.
```ReferenceError: io is not defined
    at Object.<anonymous> (http://localhost:9000/app/1056f785.app.js:1:11165)
    at Object.e [as invoke] (http://localhost:9000/app/c6d9555e.vendor.js:4:19685)
    at Object.$get (http://localhost:9000/app/c6d9555e.vendor.js:4:18122)
    at Object.e [as invoke] (http://localhost:9000/app/c6d9555e.vendor.js:4:19685)
    at http://localhost:9000/app/c6d9555e.vendor.js:4:20262
    at d (http://localhost:9000/app/c6d9555e.vendor.js:4:19315)
    at e (http://localhost:9000/app/c6d9555e.vendor.js:4:19652)
    at Object.f [as instantiate] (http://localhost:9000/app/c6d9555e.vendor.js:4:19777)
    at http://localhost:9000/app/c6d9555e.vendor.js:5:9684
    at http://localhost:9000/app/c6d9555e.vendor.js:10:9103 <div id="master" ui-view="" class="ng-scope">
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Awk34** [comment]
Does the error show up when you run the un-minified code (`grunt serve`)? If so, where? What's the stack trace?

**Comment by austinkettner** [comment]
@Awk34 Nope no errors or warnings when doing ```grunt serve```. No build errors when doing ```grunt serve:dist``` either, the errors are in the compiled code and when trying to be run (Chrome Inspector)

**Comment by Awk34** [comment]
Is socket.io imported in your built `index.html`?

**Comment by austinkettner** [comment]
This was due to the order of the bower.json entries (app.js compilation) with regards to the app.coffee defined Angular Modules. They need to be delicately managed and in exactly the same order as each other.

**Comment by giancarloGiuffra** [comment]
@austinkettner hi, I'm having the same problem. Could you please explain what solved the problem? I don't understand what you mean by app.coffee defined angular modules. Thank you.
